### ISSUE TITLE
should i build the project with gitbook?

### ISSUE THREAD

**Issue by snowdream** [snowdream/awesome-android#102]
The project has to many projects, and it is too slow to browse.
should i build the project with gitbook?

**Comment by lokeshsuhas** [comment]
Yes , that will be too helpful

**Comment by ez0ne** [comment]
Support building the project with gitbook！

**Comment by krimin-killr21** [comment]
Yeah, seems like a good idea. Much more suited to this use case certainly.

**Comment by tarek360** [comment]
If you have some time for that, it will be nice idea.
Thank you.

**Comment by snowdream** [comment]
fix #102  06699e17537ab7681c1d07d41b6972ab659d894b
